
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `deval`=list(
        `type`="software", 
        `author`="Pessina, A. L. R.", 
        `year`=2025, 
        `title`="deval: Diagnostic Test Evaluation", 
        `publisher`="(0.1.4) [jamovi module]. DOI available on https://github.com/apessina/jamovi-deval", 
        `url`="https://github.com/apessina/jamovi-deval"), 
    `pROC`=list(
        `type`="article", 
        `author`="Robin, X. et al.", 
        `year`=2011, 
        `title`="pROC: an open-source package for R and S+ to analyze and compare ROC curves", 
        `publisher`="BMC Bioinformatics", 
        `volume`=12, 
        `pages`="77"))
