
# This file is automatically generated, you probably don't want to edit this

rocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pred = NULL,
            resp = NULL,
            ciWidth = 95,
            boolz = FALSE,
            direction = "auto",
            medians = FALSE,
            means = FALSE,
            suggest = FALSE,
            coLines = 5,
            sortBy = "closest.topleft",
            decrease = FALSE,
            cRates = list(
                "tpr",
                "fpr"),
            pMetrics = NULL,
            pValue = NULL,
            cIndex = NULL, ...) {

            super$initialize(
                package="deval",
                name="roc",
                requiresData=TRUE,
                ...)

            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..resp <- jmvcore::OptionVariable$new(
                "resp",
                resp,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..boolz <- jmvcore::OptionBool$new(
                "boolz",
                boolz,
                default=FALSE)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    "auto",
                    "greater",
                    "less"),
                default="auto")
            private$..medians <- jmvcore::OptionBool$new(
                "medians",
                medians,
                default=FALSE)
            private$..means <- jmvcore::OptionBool$new(
                "means",
                means,
                default=FALSE)
            private$..suggest <- jmvcore::OptionBool$new(
                "suggest",
                suggest,
                default=FALSE)
            private$..coLines <- jmvcore::OptionNumber$new(
                "coLines",
                coLines,
                min=1,
                max=10,
                default=5)
            private$..sortBy <- jmvcore::OptionList$new(
                "sortBy",
                sortBy,
                options=list(
                    "closest.topleft",
                    "youden",
                    "tpr",
                    "tnr"),
                default="closest.topleft")
            private$..decrease <- jmvcore::OptionBool$new(
                "decrease",
                decrease,
                default=FALSE)
            private$..cRates <- jmvcore::OptionNMXList$new(
                "cRates",
                cRates,
                options=list(
                    "tpr",
                    "fpr",
                    "tnr",
                    "fnr"),
                default=list(
                    "tpr",
                    "fpr"))
            private$..pMetrics <- jmvcore::OptionNMXList$new(
                "pMetrics",
                pMetrics,
                options=list(
                    "accu",
                    "bAccu"),
                default=NULL)
            private$..pValue <- jmvcore::OptionNMXList$new(
                "pValue",
                pValue,
                options=list(
                    "prec",
                    "npv"),
                default=NULL)
            private$..cIndex <- jmvcore::OptionNMXList$new(
                "cIndex",
                cIndex,
                options=list(
                    "tl",
                    "yo"),
                default=NULL)

            self$.addOption(private$..pred)
            self$.addOption(private$..resp)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..boolz)
            self$.addOption(private$..direction)
            self$.addOption(private$..medians)
            self$.addOption(private$..means)
            self$.addOption(private$..suggest)
            self$.addOption(private$..coLines)
            self$.addOption(private$..sortBy)
            self$.addOption(private$..decrease)
            self$.addOption(private$..cRates)
            self$.addOption(private$..pMetrics)
            self$.addOption(private$..pValue)
            self$.addOption(private$..cIndex)
        }),
    active = list(
        pred = function() private$..pred$value,
        resp = function() private$..resp$value,
        ciWidth = function() private$..ciWidth$value,
        boolz = function() private$..boolz$value,
        direction = function() private$..direction$value,
        medians = function() private$..medians$value,
        means = function() private$..means$value,
        suggest = function() private$..suggest$value,
        coLines = function() private$..coLines$value,
        sortBy = function() private$..sortBy$value,
        decrease = function() private$..decrease$value,
        cRates = function() private$..cRates$value,
        pMetrics = function() private$..pMetrics$value,
        pValue = function() private$..pValue$value,
        cIndex = function() private$..cIndex$value),
    private = list(
        ..pred = NA,
        ..resp = NA,
        ..ciWidth = NA,
        ..boolz = NA,
        ..direction = NA,
        ..medians = NA,
        ..means = NA,
        ..suggest = NA,
        ..coLines = NA,
        ..sortBy = NA,
        ..decrease = NA,
        ..cRates = NA,
        ..pMetrics = NA,
        ..pValue = NA,
        ..cIndex = NA)
)

rocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocResults",
    inherit = jmvcore::Group,
    active = list(
        tableMain = function() private$.items[["tableMain"]],
        tableDir = function() private$.items[["tableDir"]],
        tableCo = function() private$.items[["tableCo"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ROC Analysis for Continuous Predictor")
            self$add(jmvcore::Table$new(
                options=options,
                name="tableMain",
                title="Area Under the Curve",
                rows="(pred)",
                notes=list(
                    `hip`=NULL),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="auc", 
                        `title`="AUC", 
                        `type`="number"),
                    list(
                        `name`="cil", 
                        `title`="Lower", 
                        `superTitle`="Confidence Interval", 
                        `type`="number"),
                    list(
                        `name`="ciu", 
                        `title`="Upper", 
                        `superTitle`="Confidence Interval", 
                        `type`="number"),
                    list(
                        `name`="statistics", 
                        `title`="Statistics", 
                        `superTitle`="Z-Test (DeLong)", 
                        `type`="number", 
                        `visible`="(boolz)"),
                    list(
                        `name`="pvalue", 
                        `title`="p-value", 
                        `superTitle`="Z-Test (DeLong)", 
                        `type`="number", 
                        `visible`="(boolz)", 
                        `format`="zto,pvalue")),
                refs=list(
                    "deval",
                    "pROC")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableDir",
                visible="(medians || means || suggest)",
                title="Test Direction",
                rows="(pred)",
                notes=list(
                    `hip`=NULL),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="control_median", 
                        `title`="Control", 
                        `superTitle`="Median", 
                        `type`="number", 
                        `visible`="(medians)"),
                    list(
                        `name`="case_median", 
                        `title`="Case", 
                        `superTitle`="Median", 
                        `type`="number", 
                        `visible`="(medians)"),
                    list(
                        `name`="control_mean", 
                        `title`="Control", 
                        `superTitle`="Mean", 
                        `type`="number", 
                        `visible`="(means)"),
                    list(
                        `name`="case_mean", 
                        `title`="Case", 
                        `superTitle`="Mean", 
                        `type`="number", 
                        `visible`="(means)"),
                    list(
                        `name`="suggest", 
                        `title`="Suggested Direction", 
                        `type`="text", 
                        `visible`="(suggest)")),
                refs=list(
                    "deval")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableCo",
                visible="(cRates:tpr || cRates:fpr || cRates:tnr || cRates:fnr || pMetrics:accu || pMetrics:bAccu || pValue:prec || pValue:npv || cIndex:tl || cIndex:yo)",
                title="Local Maximas",
                notes=list(
                    `dir`=NULL),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Cutoff", 
                        `title`="Cut-off", 
                        `type`="number"),
                    list(
                        `name`="TPR", 
                        `visible`="(cRates:tpr)", 
                        `title`="Sensitivity (TPR)", 
                        `type`="number"),
                    list(
                        `name`="FPR", 
                        `visible`="(cRates:fpr)", 
                        `title`="1-Specificity (FPR)", 
                        `type`="number"),
                    list(
                        `name`="TNR", 
                        `visible`="(cRates:tnr)", 
                        `title`="Specificity (TNR)", 
                        `type`="number"),
                    list(
                        `name`="FNR", 
                        `visible`="(cRates:fnr)", 
                        `title`="1-Sensitivity (FNR)", 
                        `type`="number"),
                    list(
                        `name`="Accuracy", 
                        `visible`="(pMetrics:accu)", 
                        `type`="number"),
                    list(
                        `name`="bAccu", 
                        `title`="Bal. Accuracy", 
                        `visible`="(pMetrics:bAccu)", 
                        `type`="number"),
                    list(
                        `name`="Precision", 
                        `visible`="(pValue:prec)", 
                        `type`="number"),
                    list(
                        `name`="NPV", 
                        `visible`="(pValue:npv)", 
                        `type`="number"),
                    list(
                        `name`="Topleft", 
                        `visible`="(cIndex:tl)", 
                        `title`="Top-left dist.", 
                        `type`="number"),
                    list(
                        `name`="Youden", 
                        `visible`="(cIndex:yo)", 
                        `title`="Youden\u2019s J", 
                        `type`="number")),
                refs=list(
                    "deval",
                    "pROC")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="ROC Curve",
                width=400,
                height=400,
                renderFun=".plot",
                refs=list(
                    "deval",
                    "pROC")))}))

rocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "deval",
                name = "roc",
                version = c(0,2,0),
                options = options,
                results = rocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ROC Analysis for Continuous Predictor
#'
#' 
#' @param data .
#' @param pred .
#' @param resp .
#' @param ciWidth .
#' @param boolz .
#' @param direction .
#' @param medians .
#' @param means .
#' @param suggest .
#' @param coLines .
#' @param sortBy .
#' @param decrease .
#' @param cRates .
#' @param pMetrics .
#' @param pValue .
#' @param cIndex .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tableMain} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableDir} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableCo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableMain$asDF}
#'
#' \code{as.data.frame(results$tableMain)}
#'
#' @export
roc <- function(
    data,
    pred,
    resp,
    ciWidth = 95,
    boolz = FALSE,
    direction = "auto",
    medians = FALSE,
    means = FALSE,
    suggest = FALSE,
    coLines = 5,
    sortBy = "closest.topleft",
    decrease = FALSE,
    cRates = list(
                "tpr",
                "fpr"),
    pMetrics = NULL,
    pValue = NULL,
    cIndex = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("roc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if ( ! missing(resp)) resp <- jmvcore::resolveQuo(jmvcore::enquo(resp))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pred), pred, NULL),
            `if`( ! missing(resp), resp, NULL))

    for (v in resp) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rocOptions$new(
        pred = pred,
        resp = resp,
        ciWidth = ciWidth,
        boolz = boolz,
        direction = direction,
        medians = medians,
        means = means,
        suggest = suggest,
        coLines = coLines,
        sortBy = sortBy,
        decrease = decrease,
        cRates = cRates,
        pMetrics = pMetrics,
        pValue = pValue,
        cIndex = cIndex)

    analysis <- rocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

