
# This file is automatically generated, you probably don't want to edit this

rocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varPred = NULL,
            varOutc = NULL,
            DeLongCl = 95,
            boolz = FALSE,
            boolCo = FALSE,
            cRates = list(
                "tpr",
                "fpr"),
            pMetrics = NULL,
            pValue = NULL,
            cIndex = NULL, ...) {

            super$initialize(
                package="deval",
                name="roc",
                requiresData=TRUE,
                ...)

            private$..varPred <- jmvcore::OptionVariable$new(
                "varPred",
                varPred,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..varOutc <- jmvcore::OptionVariable$new(
                "varOutc",
                varOutc,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..DeLongCl <- jmvcore::OptionNumber$new(
                "DeLongCl",
                DeLongCl,
                min=50,
                max=99.9,
                default=95)
            private$..boolz <- jmvcore::OptionBool$new(
                "boolz",
                boolz,
                default=FALSE)
            private$..boolCo <- jmvcore::OptionBool$new(
                "boolCo",
                boolCo,
                default=FALSE)
            private$..cRates <- jmvcore::OptionNMXList$new(
                "cRates",
                cRates,
                options=list(
                    "tpr",
                    "fpr",
                    "tnr",
                    "fnr"),
                default=list(
                    "tpr",
                    "fpr"))
            private$..pMetrics <- jmvcore::OptionNMXList$new(
                "pMetrics",
                pMetrics,
                options=list(
                    "accu",
                    "bAccu"),
                default=NULL)
            private$..pValue <- jmvcore::OptionNMXList$new(
                "pValue",
                pValue,
                options=list(
                    "prec",
                    "npv"),
                default=NULL)
            private$..cIndex <- jmvcore::OptionNMXList$new(
                "cIndex",
                cIndex,
                options=list(
                    "tl",
                    "yo"),
                default=NULL)

            self$.addOption(private$..varPred)
            self$.addOption(private$..varOutc)
            self$.addOption(private$..DeLongCl)
            self$.addOption(private$..boolz)
            self$.addOption(private$..boolCo)
            self$.addOption(private$..cRates)
            self$.addOption(private$..pMetrics)
            self$.addOption(private$..pValue)
            self$.addOption(private$..cIndex)
        }),
    active = list(
        varPred = function() private$..varPred$value,
        varOutc = function() private$..varOutc$value,
        DeLongCl = function() private$..DeLongCl$value,
        boolz = function() private$..boolz$value,
        boolCo = function() private$..boolCo$value,
        cRates = function() private$..cRates$value,
        pMetrics = function() private$..pMetrics$value,
        pValue = function() private$..pValue$value,
        cIndex = function() private$..cIndex$value),
    private = list(
        ..varPred = NA,
        ..varOutc = NA,
        ..DeLongCl = NA,
        ..boolz = NA,
        ..boolCo = NA,
        ..cRates = NA,
        ..pMetrics = NA,
        ..pValue = NA,
        ..cIndex = NA)
)

rocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocResults",
    inherit = jmvcore::Group,
    active = list(
        tableMain = function() private$.items[["tableMain"]],
        tablez = function() private$.items[["tablez"]],
        tableCo = function() private$.items[["tableCo"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ROC Analysis for Continuous Predictor")
            self$add(jmvcore::Table$new(
                options=options,
                name="tableMain",
                title="Area Under the ROC Curve",
                rows=1,
                notes=list(
                    `CI`="Normal-based CI with AUC variance from DeLong's method"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="AUC", 
                        `type`="number"),
                    list(
                        `name`="CI", 
                        `title`="Confidence interval", 
                        `type`="text")),
                refs=list(
                    "deval",
                    "pROC")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tablez",
                visible="(boolz)",
                title="z-test for AUC",
                rows=1,
                notes=list(
                    `hip`="H\u2081: AUC \u2260 0.5"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Statistics", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                refs=list(
                    "deval",
                    "pROC")))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableCo",
                visible="(boolCo)",
                title="Cut-offs",
                notes=list(
                    `dir`=NULL),
                columns=list(
                    list(
                        `name`="Cutoff", 
                        `title`="Cut-off", 
                        `type`="number"),
                    list(
                        `name`="TPR", 
                        `visible`="(cRates:tpr)", 
                        `title`="Sensitivity (TPR)", 
                        `type`="number"),
                    list(
                        `name`="FPR", 
                        `visible`="(cRates:fpr)", 
                        `title`="1-Specificity (FPR)", 
                        `type`="number"),
                    list(
                        `name`="TNR", 
                        `visible`="(cRates:tnr)", 
                        `title`="Specificity (TNR)", 
                        `type`="number"),
                    list(
                        `name`="FNR", 
                        `visible`="(cRates:fnr)", 
                        `title`="1-Sensitivity (FNR)", 
                        `type`="number"),
                    list(
                        `name`="Accuracy", 
                        `visible`="(pMetrics:accu)", 
                        `type`="number"),
                    list(
                        `name`="bAccu", 
                        `title`="Bal. Accuracy", 
                        `visible`="(pMetrics:bAccu)", 
                        `type`="number"),
                    list(
                        `name`="Precision", 
                        `visible`="(pValue:prec)", 
                        `type`="number"),
                    list(
                        `name`="NPV", 
                        `visible`="(pValue:npv)", 
                        `type`="number"),
                    list(
                        `name`="Topleft", 
                        `visible`="(cIndex:tl)", 
                        `title`="Top-left dist.", 
                        `type`="number"),
                    list(
                        `name`="Youden", 
                        `visible`="(cIndex:yo)", 
                        `title`="Youden\u2019s J", 
                        `type`="number")),
                refs=list(
                    "deval",
                    "pROC")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="ROC Curve",
                width=400,
                height=400,
                renderFun=".plot",
                refs=list(
                    "deval",
                    "pROC")))}))

rocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "deval",
                name = "roc",
                version = c(0,1,3),
                options = options,
                results = rocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ROC Analysis for Continuous Predictor
#'
#' 
#' @param data .
#' @param varPred .
#' @param varOutc .
#' @param DeLongCl .
#' @param boolz .
#' @param boolCo .
#' @param cRates .
#' @param pMetrics .
#' @param pValue .
#' @param cIndex .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tableMain} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tablez} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableCo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableMain$asDF}
#'
#' \code{as.data.frame(results$tableMain)}
#'
#' @export
roc <- function(
    data,
    varPred,
    varOutc,
    DeLongCl = 95,
    boolz = FALSE,
    boolCo = FALSE,
    cRates = list(
                "tpr",
                "fpr"),
    pMetrics = NULL,
    pValue = NULL,
    cIndex = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("roc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varPred)) varPred <- jmvcore::resolveQuo(jmvcore::enquo(varPred))
    if ( ! missing(varOutc)) varOutc <- jmvcore::resolveQuo(jmvcore::enquo(varOutc))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varPred), varPred, NULL),
            `if`( ! missing(varOutc), varOutc, NULL))

    for (v in varOutc) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rocOptions$new(
        varPred = varPred,
        varOutc = varOutc,
        DeLongCl = DeLongCl,
        boolz = boolz,
        boolCo = boolCo,
        cRates = cRates,
        pMetrics = pMetrics,
        pValue = pValue,
        cIndex = cIndex)

    analysis <- rocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

